//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart_Detalle
    {
        public int id_shoppingcart_detalle { get; set; }
        public int id_shopping_cart { get; set; }
        public int id_lista_producto { get; set; }
        public int id_estado { get; set; }
    
        public virtual Detalle_Prodducto Detalle_Prodducto { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Shopping_Cart Shopping_Cart { get; set; }
    }
}
