//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shopping_Cart()
        {
            this.Shopping_Cart_Detalle = new HashSet<Shopping_Cart_Detalle>();
        }
    
        public int id_shoppingcart { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime date { get; set; }
        public int estado { get; set; }
        public Nullable<int> metodo_pag { get; set; }
        public decimal monto_total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Metodo_Pago Metodo_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_Cart_Detalle> Shopping_Cart_Detalle { get; set; }
    }
}
